### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by tuomas2** [AndBible/LBCF1689FIN#2]
![image](https://user-images.githubusercontent.com/5811789/203798125-121d1085-7e87-40d6-b346-0a0d0d4c0781.png)

Pitäisi lukea: 'elettyään luonnollisessa tilassaan ilman Henkeä...'

**Comment by tuomas2** [comment]
@mkoponen onko tämä sinun versiossa korjattu?

**Comment by mkoponen** [comment]
> @mkoponen onko tämä sinun versiossa korjattu?

Tekstissä on pari alaviitettä, jotka olen merkinnyt asteriskilla, ja sitten sijoittanut sen kappaleen alapuolelle pienemmällä fontilla. Varsinaiseen alaviiteosioon ei kannata sotkea numeroituja alaviitteitä ja asteriskeja. Epub:ssa tämä on ollut alusta asti oikein. Oletan siis että parserisi on vain tehnyt tässä kohtaa huonon valinnan, ja tunnistanut sen kylläkin viittaukseksi, mutta sijoittanut sen tekstin sekaan.

**Comment by mkoponen** [comment]
Pitäisi siis olla: ...elettyään luonnollisessa* tilassaan jonkun aikaa...
*ilman Henkeä

2. Ei ole ketään...

**Comment by tuomas2** [comment]
Aivan, tuohan on oikein xml:ssä, pelkästään tuossa html:ssä väärin kun siinä inlinetetään (crossreferencejen) footnotet.

**Comment by tuomas2** [comment]
Laitoin tyypiksi "explanation" ja muut kuin crossReference-tyyppiset footnotet sulkuihin css:llä.
